version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      uno-and-skia:
        patterns: ['Uno.*', 'SkiaSharp*']
      test-tools:
        patterns: ['xunit*', 'Microsoft.NET.Test.Sdk', 'DocumentFormat.OpenXml*']
