from pathlib import Path
import hashlib

# All modifications are guarded by the exact reviewed baseline blob revision.
def patch(path, expected, edits):
    p = Path(path)
    original = p.read_bytes()
    actual = hashlib.sha1(b'blob ' + str(len(original)).encode() + b'\0' + original).hexdigest()
    assert actual == expected, f'Unexpected source revision: {path}'
    text = original.decode('utf-8')
    for start, end, replacement in reversed(edits):
        text = text[:start] + replacement + text[end:]
    p.write_text(text, encoding='utf-8')

patch('src/PresentationSpace.App/PresentationSpace.App.csproj', 'ef71f81e9f61a70894048bcd4ffe5d5458527181', [(482, 589, '    <ApplicationDisplayVersion>0.3.0</ApplicationDisplayVersion><ApplicationVersion>3</ApplicationVersion>\n')])
patch('src/PresentationSpace.Controls.Uno/ChartDataEditor.cs', '90ef543ba4bd81abd7ba0fc827210f2ffc80e6ba', [(2401, 2806, '        body.Children.Add(new TextBlock { Text = "Paste category + series columns. Empty numbers stay missing. Apply commits data, title and hole size before leaving the pane.", TextWrapping = TextWrapping.Wrap, FontSize = 11, Foreground = OfficePalette.Muted });\n'), (3115, 3115, '        body.Children.Add(new TextBlock { Text = "Chart background", FontSize = 12 });\n        var background = new ColorPalette(); background.ColorSelected += (_, color) => Update(c => c with { Background = color }); body.Children.Add(background);\n')])
patch('src/PresentationSpace.Controls.Uno/FormatPane.cs', '35a3e04fcefde58f451ca4e50d98eb792ffbcdca', [(3627, 3728, '                    _chartEditor=new ChartDataEditor{IsEnabled=!shape.Locked};_chartEditor.SetValue(ChartModel.Get(shape));\n')])
patch('src/PresentationSpace.Core/ChartModel.cs', '785cea04c971bac7486b025bccc9252e1c0f0689', [(828, 828, '    public string Background { get; init; } = "#FFFFFF";\n'), (1997, 2048, '            ShowLegend = false, ShowValues = true, Background = "#00000000",\n'), (3094, 3257, '        if (c.Title is null || c.Title.Length > 32767 || !ValidColor(c.Background) || c.HoleSize is < 10 or > 90) throw new InvalidDataException("Invalid chart title or doughnut hole size.");\n')])
patch('src/PresentationSpace.Core/EditorSession.cs', '010fd831f5ad1eda364c4b4f57d393592a0348a1', [(4721, 4866, '        EditSlide(label, s => s with { Shapes = s.Shapes.Select(x => Selection.Contains(x.Id) && !x.Locked ? ReconcileChartFill(x, edit(x)) : x).ToImmutableArray() });\n    }\n    private static SlideShape ReconcileChartFill(SlideShape before, SlideShape after)\n    {\n        if (before.Kind != ShapeKind.Chart || after.Kind != ShapeKind.Chart || before.Chart is not { } chart || !ReferenceEquals(chart, after.Chart) || before.Fill == after.Fill) return after;\n        return ChartModel.Apply(after, chart with { Series = chart.Series.SetItem(0, chart.Series[0] with { Color = after.Fill }) });\n'), (7860, 7860, '        if (kind == ShapeKind.Chart)\n        {\n            Insert(ChartModel.Apply(new SlideShape\n            {\n                Name = "Chart " + (CurrentSlide.Shapes.Length + 1),\n                Bounds = new(Document.Width * .2f, Document.Height * .3f, Document.Width * .6f, Document.Height * .6f)\n            }, new ChartSpec\n            {\n                Title = "Chart title", Categories = ["Q1", "Q2", "Q3", "Q4"],\n                Series = [new() { Name = "Series 1", Values = [42, 68, 54, 89] }]\n            }));\n            return;\n        }\n')])
patch('src/PresentationSpace.Core/SlideFactory.cs', '7f91f50078fd374bb0b1dd57ff2b54c0089ed552', [(4950, 5248, '        SlideShape Retheme(SlideShape shape)\n        {\n            var result = shape with { Fill = shape.Fill == old ? accent : shape.Fill, TextStyle = shape.TextStyle with { Color = shape.TextStyle.Color == old ? accent : shape.TextStyle.Color } };\n            if (shape.Chart is { } chart)\n                result = ChartModel.Apply(result, chart with { Series = chart.Series.Select(series => series.Color == old ? series with { Color = accent } : series).ToImmutableArray() });\n            return result;\n        }\n        return d with { Theme = name, Slides = d.Slides.Select(s => s with { Shapes = s.Shapes.Select(Retheme).ToImmutableArray() }).ToImmutableArray() };\n')])
patch('src/PresentationSpace.Formats/PptxCodec.Charts.cs', 'cd22629c015c8158b267f913df82f4a1b703be3e', [(6433, 6813, '        var root = new XElement(C + "chartSpace", new XAttribute(XNamespace.Xmlns + "c", C), new XAttribute(XNamespace.Xmlns + "a", A), new XAttribute(XNamespace.Xmlns + "r", R), ChartValue("date1904", 0), ChartValue("lang", "en-US"), ChartValue("roundedCorners", 0), chart, new XElement(C + "spPr", Fill(spec.Background, shape.Opacity)), new XElement(C + "externalData", new XAttribute(R + "id", "rIdWorkbook"), ChartValue("autoUpdate", 0)));\n'), (17701, 17821, '            Kind = kind, Grouping = grouping, Title = titleText, Background = color(root.Element(C + "spPr"), "#FFFFFF"), ShowLegend = chart?.Element(C + "legend") is not null,\n')])
patch('src/PresentationSpace.Rendering.Skia/SlideRenderer.Charts.cs', 'ebf85a91f77b7e6a956a907482cba919258e390e', [(876, 876, '            using (var background = new SKPaint { Color = Color(chart.Background) }) canvas.DrawRect(0, 0, 640, 360, background);\n')])

for name in ['ChartCommandTests.cs', 'ChartPresentationTests.cs']:
    destination = Path('tests/PresentationSpace.Tests') / name
    assert not destination.exists()
    destination.write_bytes((Path('.ci-chart-finalize') / name).read_bytes())
