"""Exercise the production Uno app with real Chromium keyboard input and rendered pixels."""
import io
import json
import os
import time
from pathlib import Path
from PIL import Image
from playwright.sync_api import sync_playwright

output = Path('artifacts/screenshots')
output.mkdir(parents=True, exist_ok=True)
url = os.environ.get('PRESENTATIONSPACE_URL', 'http://127.0.0.1:8080/PresentationSpace/')
errors, console = [], []

with sync_playwright() as playwright:
    options = {'headless': True, 'args': ['--no-sandbox', '--enable-unsafe-swiftshader', '--use-angle=swiftshader']}
    if os.environ.get('CHROMIUM_EXECUTABLE'):
        options['executable_path'] = os.environ['CHROMIUM_EXECUTABLE']
    browser = playwright.chromium.launch(**options)
    context = browser.new_context(viewport={'width': 1440, 'height': 960}, device_scale_factor=1)
    page = context.new_page()
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.on('console', lambda message: console.append(f'{message.type}: {message.text}'))
    def attr(name, value):
        page.wait_for_function('(args) => document.documentElement.getAttribute(args[0]) === args[1]', arg=[name, str(value)], timeout=20000)
    def painted_editor():
        deadline = time.monotonic() + 30
        while time.monotonic() < deadline:
            image = Image.open(io.BytesIO(page.screenshot(clip={'x': 0, 'y': 0, 'width': 220, 'height': 44}))).convert('RGB')
            accent_pixels = sum(1 for r, g, b in image.getdata() if r > 170 and 40 < g < 135 and b < 110)
            if accent_pixels > 150:
                return
            page.wait_for_timeout(150)
        raise AssertionError('The editor title bar was not visibly rendered, or a modal blocked startup.')
    def command(text):
        before = int(page.locator('html').get_attribute('data-command-version'))
        page.keyboard.press('Alt+q')
        # Verify previous commands really cleared the product's input, rather than clearing it in the test.
        page.wait_for_function("() => document.activeElement?.id === 'uno-input' && document.activeElement.tagName === 'INPUT' && document.activeElement.value === ''", timeout=20000)
        page.keyboard.type(text)
        page.keyboard.press('Enter')
        attr('data-command-version', before + 1)
    try:
        page.goto(url, wait_until='domcontentloaded', timeout=60000)
        page.wait_for_function("document.documentElement.getAttribute('data-presentationspace') === 'ready' || document.documentElement.hasAttribute('data-startup-error')", timeout=120000)
        startup_error = page.locator('html').get_attribute('data-startup-error')
        assert not startup_error, startup_error
        attr('data-slide-count', 4)
        painted_editor()
        page.screenshot(path=str(output / 'editor.png'), full_page=True)
        assert page.locator('canvas').count() > 0, 'No Skia canvas was created.'
        print('PASS: startup and visibly painted editor; no fresh-session recovery prompt.', flush=True)
        page.keyboard.press('Control+m')
        attr('data-slide-count', 5)
        page.keyboard.press('Control+z')
        attr('data-slide-count', 4)
        page.keyboard.press('Control+y')
        attr('data-slide-count', 5)
        print('PASS: new slide and undo/redo.', flush=True)
        command('Insert rectangle')
        attr('data-selection-count', 1)
        count = int(page.locator('html').get_attribute('data-shape-count'))
        page.keyboard.press('ArrowRight')
        page.keyboard.press('Control+d')
        attr('data-shape-count', count + 1)
        page.keyboard.press('Control+z')
        attr('data-shape-count', count)
        page.screenshot(path=str(output / 'editing.png'), full_page=True)
        print('PASS: command search, insertion, nudging, duplication and undo.', flush=True)
        command('Insert text box')
        page.wait_for_function("() => document.activeElement?.id === 'uno-input' && document.activeElement.tagName === 'TEXTAREA'", timeout=20000)
        page.keyboard.type('Alpha Beta Gamma')
        page.keyboard.press('Control+Home')
        for _ in range(5):
            page.keyboard.press('Shift+ArrowRight')
        page.wait_for_function("() => document.activeElement?.selectionStart === 0 && document.activeElement?.selectionEnd === 5", timeout=20000)
        page.keyboard.press('Control+b')
        attr('data-primary-text-length', 16)
        attr('data-primary-range-count', 1)
        attr('data-primary-range-start', 0)
        attr('data-primary-range-length', 5)
        page.keyboard.press('Escape')
        page.keyboard.press('Control+z')
        attr('data-primary-range-count', 0)
        page.keyboard.press('Control+y')
        attr('data-primary-range-count', 1)
        text_length = page.locator('html').get_attribute('data-text-length')
        shape_count = page.locator('html').get_attribute('data-shape-count')
        command('Apply Blank layout')
        attr('data-active-layout', 'Blank')
        attr('data-text-length', text_length)
        attr('data-shape-count', shape_count)
        command('Apply Title only layout')
        attr('data-active-layout', 'Title only')
        attr('data-text-length', text_length)
        attr('data-primary-range-count', 1)
        page.screenshot(path=str(output / 'rich-text-layout.png'), full_page=True)
        print('PASS: partial text formatting via Ctrl+B, exact range, undo/redo and non-destructive layout changes.', flush=True)
        command('Insert chart')
        attr('data-chart-series', 1)
        command('Edit chart data')
        page.wait_for_function("() => document.activeElement?.id === 'uno-input' && document.activeElement.tagName === 'TEXTAREA'", timeout=20000)
        page.keyboard.insert_text('Category\tActual\tPlan\nQ1\t10\t15\nQ2\t\t18\nQ3\t25\t22')
        page.keyboard.press('Control+Enter')
        attr('data-chart-series', 2)
        attr('data-chart-categories', 3)
        attr('data-chart-missing', 1)
        command('Chart type Line')
        attr('data-chart-type', 'Line')
        page.screenshot(path=str(output / 'chart-line.png'), full_page=True)
        command('Chart type Bar')
        command('Chart grouping Stacked')
        attr('data-chart-type', 'Bar')
        attr('data-chart-grouping', 'Stacked')
        page.keyboard.press('Control+z')
        attr('data-chart-grouping', 'Clustered')
        page.keyboard.press('Control+y')
        attr('data-chart-grouping', 'Stacked')
        page.screenshot(path=str(output / 'chart-stacked.png'), full_page=True)
        command('Edit chart data')
        page.wait_for_function("() => document.activeElement?.id === 'uno-input' && document.activeElement.tagName === 'TEXTAREA'", timeout=20000)
        page.keyboard.insert_text('Category\tRevenue\nProduct A\t45\nProduct B\t30\nProduct C\t25')
        page.keyboard.press('Control+Enter')
        attr('data-chart-series', 1)
        command('Chart type Doughnut')
        attr('data-chart-type', 'Doughnut')
        page.screenshot(path=str(output / 'chart-doughnut.png'), full_page=True)
        print('PASS: real chart-data input, two series, missing values, type changes, stacked grouping, undo/redo and doughnut conversion.', flush=True)
        command('New slide')
        attr('data-slide-count', 6)
        page.keyboard.press('Control+a')
        page.keyboard.press('Delete')
        attr('data-shape-count', 0)
        command('Insert table')
        attr('data-table-rows', 4)
        attr('data-table-columns', 3)
        attr('data-table-origins', 12)
        command('Edit table data')
        page.wait_for_function("() => document.activeElement?.id === 'uno-input' && document.activeElement.tagName === 'TEXTAREA'", timeout=20000)
        page.keyboard.insert_text('Updated category')
        page.keyboard.press('Control+Enter')
        # Merging preserves content in reading order, adding two paragraph separators.
        text_length = int(page.locator('html').get_attribute('data-table-text-length'))
        command('Table select row')
        command('Merge table cells')
        attr('data-table-origins', 10)
        attr('data-table-merged', 1)
        attr('data-table-text-length', text_length + 2)
        page.screenshot(path=str(output / 'table-merged.png'), full_page=True)
        page.keyboard.press('Control+z')
        attr('data-table-origins', 12)
        page.keyboard.press('Control+y')
        attr('data-table-origins', 10)
        command('Split table cell')
        attr('data-table-origins', 12)
        attr('data-table-merged', 0)
        command('Insert table row')
        attr('data-table-rows', 5)
        command('Insert table column')
        attr('data-table-columns', 4)
        command('Delete table column')
        attr('data-table-columns', 3)
        page.screenshot(path=str(output / 'table-layout.png'), full_page=True)
        print('PASS: cell input, range merging/splitting, content preservation, track insertion/deletion and table undo/redo.', flush=True)
        # Return to the populated table and edit the merged heading through real input.
        for _ in range(3):
            page.keyboard.press('Control+z')
        attr('data-table-rows', 4)
        attr('data-table-columns', 3)
        command('Table select row')
        command('Merge table cells')
        attr('data-table-origins', 10)
        command('Edit table data')
        page.wait_for_function("() => document.activeElement?.id === 'uno-input' && document.activeElement.tagName === 'TEXTAREA'", timeout=20000)
        page.keyboard.insert_text('Regional performance')
        page.keyboard.press('Control+Enter')
        attr('data-table-merged', 1)
        page.screenshot(path=str(output / 'table-styled.png'), full_page=True)
        page.keyboard.press('F5')
        attr('data-presenting', 'true')
        page.keyboard.press('ArrowRight')
        page.screenshot(path=str(output / 'slide-show.png'), full_page=True)
        page.keyboard.press('Escape')
        attr('data-presenting', 'false')
        page.set_viewport_size({'width': 1024, 'height': 768})
        page.evaluate('() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))')
        page.screenshot(path=str(output / 'compact.png'), full_page=True)
        assert not errors, '\n'.join(errors)
        print('PASS: slideshow, exit and compact viewport.', flush=True)
    finally:
        page.screenshot(path=str(output / 'final-state.png'), full_page=True)
        state = page.evaluate("() => ({attributes: Object.fromEntries([...document.documentElement.attributes].filter(a => a.name.startsWith('data-')).map(a => [a.name, a.value])), activeInput: {id: document.activeElement?.id, tag: document.activeElement?.tagName, value: document.activeElement?.value, start: document.activeElement?.selectionStart, end: document.activeElement?.selectionEnd}})")
        (output / 'state.json').write_text(json.dumps(state, indent=2), encoding='utf-8')
        (output / 'console.log').write_text('\n'.join(console), encoding='utf-8')
        (output / 'errors.json').write_text(json.dumps(errors, indent=2), encoding='utf-8')
        (output / 'dom.html').write_text(page.content(), encoding='utf-8')
        browser.close()
